# Generated by Django 4.0.4 on 2022-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181121_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='quantity',
        ),
        migrations.AddField(
            model_name='post',
            name='duedate',
            field=models.CharField(default='date', max_length=100),
        ),
    ]
