# Generated by Django 4.0.4 on 2022-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_quantity_post_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item',
            field=models.CharField(max_length=300),
        ),
    ]
