# Generated by Django 4.0.4 on 2022-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.ImageField(default='default_business.jpg', upload_to='business_pics'),
        ),
    ]
